-- PARTE 1
-- 1
SELECT APELLIDO1, APELLIDO2, NOMBRE FROM PERSONA WHERE TIPO='alumno' ORDER BY APELLIDO1 ASC, APELLIDO2 ASC, NOMBRE ASC;
-- 2
SELECT APELLIDO1, APELLIDO2, NOMBRE FROM PERSONA WHERE TIPO='alumno' AND TELEFONO IS NULL;
-- 3
SELECT APELLIDO1, APELLIDO2, NOMBRE FROM PERSONA WHERE TIPO='alumno' AND YEAR(FECHA_NACIMIENTO)='1999';
-- 4
SELECT APELLIDO1, APELLIDO2, NOMBRE FROM PERSONA WHERE TIPO='profesor' AND TELEFONO IS NULL AND NIF LIKE('%K');
-- 5
SELECT NOMBRE FROM ASIGNATURA WHERE CUATRIMESTRE=1 AND CURSO=3 AND ID_GRADO=7;
-- 6
SELECT A.APELLIDO1, A.APELLIDO2, A.NOMBRE, C.NOMBRE FROM PERSONA A INNER JOIN PROFESOR B ON A.ID=B.ID_PROFESOR INNER JOIN DEPARTAMENTO C ON B.ID_DEPARTAMENTO=C.ID ORDER BY A.APELLIDO1 ASC, A.APELLIDO2 ASC, A.NOMBRE ASC;
-- 7
SELECT A.NOMBRE, C.ANYO_INICIO, C.ANYO_FIN FROM ASIGNATURA A INNER JOIN ALUMNO_SE_MATRICULA_ASIGNATURA B ON A.ID=B.ID_ASIGNATURA INNER JOIN CURSO_ESCOLAR C ON B.ID_CURSO_ESCOLAR=C.ID INNER JOIN PERSONA D ON B.ID_ALUMNO=D.ID WHERE D.NIF = '26902806M';
-- 8
SELECT A.NOMBRE FROM DEPARTAMENTO A INNER JOIN PROFESOR B ON A.ID=B.ID_DEPARTAMENTO INNER JOIN ASIGNATURA C ON B.ID_PROFESOR=C.ID_PROFESOR INNER JOIN GRADO D ON C.ID_GRADO=D.ID WHERE D.ID=4 GROUP BY A.NOMBRE;
-- 9
SELECT A.APELLIDO1, A.APELLIDO2, A.NOMBRE FROM PERSONA A INNER JOIN ALUMNO_SE_MATRICULA_ASIGNATURA B ON A.ID=B.ID_ALUMNO WHERE B.ID_ASIGNATURA IS NOT NULL AND B.ID_CURSO_ESCOLAR=5 GROUP BY A.APELLIDO1, A.APELLIDO2, A.NOMBRE;

-- PARTE 2
-- 1
SELECT C.ID, C.NOMBRE AS 'NOMBRE DEPARTAMENTO', A.APELLIDO1, A.APELLIDO2, A.NOMBRE FROM PERSONA A RIGHT JOIN PROFESOR B ON A.ID = B.ID_PROFESOR RIGHT JOIN DEPARTAMENTO C ON B.ID_DEPARTAMENTO = C.ID ORDER BY C.NOMBRE ASC, A.APELLIDO1 ASC, A.APELLIDO2 ASC, A.NOMBRE ASC;
-- 2
SELECT C.ID, C.NOMBRE AS 'NOMBRE DEPARTAMENTO', A.APELLIDO1, A.APELLIDO2, A.NOMBRE FROM PERSONA A RIGHT JOIN PROFESOR B ON A.ID = B.ID_PROFESOR LEFT JOIN DEPARTAMENTO C ON B.ID_DEPARTAMENTO = C.ID WHERE B.ID_DEPARTAMENTO IS NULL;
-- 3
SELECT C.ID, C.NOMBRE AS 'NOMBRE DEPARTAMENTO', A.APELLIDO1, A.APELLIDO2, A.NOMBRE FROM PERSONA A RIGHT JOIN PROFESOR B ON A.ID = B.ID_PROFESOR RIGHT JOIN DEPARTAMENTO C ON B.ID_DEPARTAMENTO = C.ID WHERE A.NOMBRE IS NULL;
-- 4
SELECT C.ID, C.NOMBRE AS 'NOMBRE ASIGNATURA', A.APELLIDO1, A.APELLIDO2, A.NOMBRE FROM PERSONA A RIGHT JOIN PROFESOR B ON A.ID = B.ID_PROFESOR LEFT JOIN ASIGNATURA C ON C.ID_PROFESOR = B.ID_PROFESOR WHERE C.NOMBRE IS NULL;
-- 5
SELECT C.ID, C.NOMBRE AS 'NOMBRE ASIGNATURA', A.APELLIDO1, A.APELLIDO2, A.NOMBRE FROM PERSONA A RIGHT JOIN PROFESOR B ON A.ID = B.ID_PROFESOR LEFT JOIN ASIGNATURA C ON C.ID_PROFESOR = B.ID_PROFESOR WHERE A.NOMBRE IS NULL;
-- 6
SELECT D.NOMBRE FROM ALUMNO_SE_MATRICULA_ASIGNATURA A LEFT JOIN ASIGNATURA B ON A.ID_CURSO_ESCOLAR = B.ID LEFT JOIN PROFESOR C ON B.ID_PROFESOR = C.ID_PROFESOR RIGHT JOIN DEPARTAMENTO D ON C.ID_DEPARTAMENTO = D.ID WHERE A.ID_CURSO_ESCOLAR IS NULL;

-- PARTE 3
-- 1
SELECT COUNT(NOMBRE) AS 'TOTAL ALUMNOS' FROM PERSONA WHERE TIPO='alumno';
-- 2
SELECT COUNT(NOMBRE) AS 'ALUMNOS NACIDOS EN 1999' FROM PERSONA WHERE TIPO='alumno' AND YEAR(FECHA_NACIMIENTO)='1999';
-- 3
SELECT C.NOMBRE AS 'DEPARTAMENTO', COUNT(A.NOMBRE) AS 'NUMERO DE PROFESORES' FROM PERSONA A INNER JOIN PROFESOR B ON A.ID = B.ID_PROFESOR INNER JOIN DEPARTAMENTO C ON B.ID_DEPARTAMENTO = C.ID GROUP BY C.NOMBRE ORDER BY COUNT(A.NOMBRE) DESC;
-- 4
SELECT C.NOMBRE AS 'DEPARTAMENTO', COUNT(A.NOMBRE) AS 'NUMERO DE PROFESORES' FROM PERSONA A INNER JOIN PROFESOR B ON A.ID = B.ID_PROFESOR RIGHT JOIN DEPARTAMENTO C ON B.ID_DEPARTAMENTO = C.ID GROUP BY C.NOMBRE ORDER BY COUNT(A.NOMBRE) DESC;
-- 5
SELECT A.NOMBRE AS 'NOMBRE GRADO', COUNT(B.NOMBRE) AS 'NUMERO DE ASIGNATURAS' FROM GRADO A LEFT JOIN ASIGNATURA B ON A.ID = B.ID_GRADO GROUP BY A.NOMBRE ORDER BY COUNT(B.NOMBRE) DESC;
-- 6
SELECT A.NOMBRE AS 'NOMBRE GRADO', COUNT(B.NOMBRE) AS 'NUMERO DE ASIGNATURAS' FROM GRADO A LEFT JOIN ASIGNATURA B ON A.ID = B.ID_GRADO GROUP BY A.NOMBRE HAVING COUNT(B.NOMBRE) > 40; 
-- 7
SELECT A.NOMBRE AS 'NOMBRE GRADO', B.TIPO AS 'TUPO ASIGNATURA', SUM(B.CREDITOS) AS 'TOTAL CREDITOS' FROM GRADO A LEFT JOIN ASIGNATURA B ON A.ID = B.ID_GRADO GROUP BY A.NOMBRE, B.TIPO;
-- 8
SELECT B.ANYO_INICIO, COUNT(DISTINCT A.ID_ALUMNO) AS 'ALUMNOS MATRICULADOS ALGUNA ASIGNATURA' FROM ALUMNO_SE_MATRICULA_ASIGNATURA A RIGHT JOIN CURSO_ESCOLAR B ON A.ID_CURSO_ESCOLAR = B.ID  GROUP BY B.ANYO_INICIO;
-- 9
SELECT A.ID, A.NOMBRE, A.APELLIDO1, A.APELLIDO2, COUNT(C.NOMBRE) FROM PERSONA A INNER JOIN PROFESOR B ON A.ID = B.ID_PROFESOR LEFT JOIN ASIGNATURA C ON B.ID_PROFESOR = C.ID_PROFESOR GROUP BY A.ID, A.NOMBRE, A.APELLIDO1, A.APELLIDO2 ORDER BY C.NOMBRE DESC;
-- 10
SELECT ID, NIF, NOMBRE, APELLIDO1, APELLIDO2, CIUDAD, DIRECCION, TELEFONO, FECHA_NACIMIENTO, SEXO, TIPO FROM PERSONA WHERE TIPO='alumno' ORDER BY FECHA_NACIMIENTO DESC LIMIT 1;
-- 11
SELECT A.NOMBRE AS 'NOMBRE PROFESOR', C.NOMBRE AS 'NOMBRE DEPARTAMENTO', D.NOMBRE AS 'NOMBRE ASIGNATURA' FROM PERSONA A INNER JOIN PROFESOR B ON A.ID = B.ID_PROFESOR INNER JOIN DEPARTAMENTO C ON B.ID_DEPARTAMENTO = C.ID LEFT JOIN ASIGNATURA D ON B.ID_PROFESOR = D.ID_PROFESOR WHERE D.NOMBRE IS NULL;
